### ISSUE TITLE
include write operations

### ISSUE THREAD

**Issue by maxlath** [maxlath/wikidata-cli#11]
As [pointed here](http://opendata.stackexchange.com/questions/9161/how-to-add-a-claim-to-an-existing-wikidata-item-from-command-line), wikidata-cli doesn't offer write operations such as adding a claim to an entity and alikes.

I see two possible paths to get there:
- integrate [wikidata-agent](https://github.com/maxlath/wikidata-agent)
- modularize wikidata-agent to use directly its logic without the server wrapper

**Comment by nichtich** [comment]
Write operations should not require a local server but store access token at a file. Aren't there any pure JavaScript Wikidata edit applications yet?!

On 29. August 2016 10:52:53 MESZ, "Maxime Lathuilière" <notifications@github.com> wrote:
>As [pointed
>here](http://opendata.stackexchange.com/questions/9161/how-to-add-a-claim-to-an-existing-wikidata-item-from-command-line),
>wikidata-cli doesn't offer write operations such as adding a claim to
>an entity and alikes.
>
>I see two possible paths to get there:
>- integrate [wikidata-agent](https://github.com/maxlath/wikidata-agent)
>- modularize wikidata-agent to use directly its logic without the
>server wrapper
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maxlath/wikidata-cli/issues/11

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by maxlath** [comment]
not that I'm aware of

The motivation for a server was to make edits with curl as simple as
```sh
curl -X POST http://localhost:4115/claim -d 'entity=Q4115189&property=P2002&value=Zorg'
```

**Comment by nichtich** [comment]
I'd move the backend of `wikidata-agent` (directory `lib`) into `wikidata-sdk` to extend the latter with write operations. [Parts of wikidata-toolkit](https://wikidata.github.io/Wikidata-Toolkit/) may be useful to look at, but a thin, opiniated wrapper on top of the API is enough. For instance:

~~~javascript
var agent = wdk.agent({ bot: 1, ...}) // general settings, including wikidata-token
item = { id: "Q123", revision: "..." } // optionally include revision. Should also support plain id
agent.setLabel(item, language, value, summary)
agent.setDescription(item, language, value, summary)
agent.setAliases(item, language, aliases, summary)
agent.addAliases(item, language, aliases, summary)
agent.removeAliases(item, language, aliases, summary)
agent.setSitelink(item, site, title, summary)
agent.addClaim(item, property, value, summary)
agent.setClaim(claim, property, value, index, summary)
agent.removeClaim(claim, summary)
agent.setQualifier(claim, property, value, summary)
...
~~~

**Comment by maxlath** [comment]
this could be an option to store the credentials: [configstore](https://github.com/yeoman/configstore)

**Comment by maxlath** [comment]
[Write operation are coming!](https://github.com/maxlath/wikidata-cli#write-operations) thank to [wikidata-edit](https://github.com/maxlath/wikidata-edit), which is basically an extraction of the work done on [wikidata-agent](https://github.com/maxlath/wikidata-agent) into a separate module.

For the config to persistent credentials, I went for [a simple json file](https://github.com/maxlath/wikidata-cli#config)

**Comment by maxlath** [comment]
done: [write operations documentation](https://github.com/maxlath/wikidata-cli/blob/master/docs/write_operations.md)
