### ISSUE TITLE
Don't write to install directory

### ISSUE THREAD

**Issue by andischan** [maxlath/wikidata-cli#16]
If you have installed wikidata-cli with your distros package manager (e.g. pacman) and not with npm, you have to run it with root rights. Otherwise you'll get:
`EACCES: permission denied, open '/usr/lib/node_modules/wikidata-cli/props/de.json'`

**Comment by maxlath** [comment]
Thanks for reporting. Isn't it a duplicate of #9?

**Comment by maxlath** [comment]
I guess a temporary fix could be to run `sudo chmod -R 666 /usr/lib/node_modules/wikidata-cli/props`, but it doesn't solve the general problem. Where should a module write files?

**Comment by andischan** [comment]
Yes, it's the same bug like #9 .

Can node apps write to ~/.config or to ~/.wikidata-cli?

**Comment by maxlath** [comment]
It could, but I would like to know first if there is a [standard and cross platform way to do that for node modules](http://stackoverflow.com/questions/41781700/where-should-a-module-write-files). Writing directly in the home folder doesn't feel super clean, maybe a subfolder like `.config` or `.local` indeed

**Comment by maxlath** [comment]
should be fixed in `4.1.2`
