### ISSUE TITLE
feature to list the history of an item

### ISSUE THREAD

**Issue by egonw** [maxlath/wikidata-cli#27]
Listing all revision of the entry in Wikidata, possibly supporting filters like, "all changes since", or "all changes by". My use case is one where I like to monitor changes to the pages I created. Using your tool and these feature I could set up a crontab allowing me to report all the changes to a set of pages (likely one CLI call for one page) since the last time I run that crontab.

**Comment by maxlath** [comment]
That could be done using [MediaWiki Revision API](https://www.mediawiki.org/wiki/API:Revisions) I guess:
 https://www.wikidata.org/w/api.php?action=query&prop=revisions&titles=Q3548931&format=json&rvstart=1497020505&rvlimit=max

We could have a `getRevisions` function [wikidata-sdk](https://github.com/maxlath/wikidata-sdk)
```js
wdk.getRevisions('Q3548931', { start: 1497021456 })
```
then wrapped in wikidata-cli:
```js
wd revisions Q3548931 --start 1497021456
```

Getting all revisions on pages modified by a user might be tricker though, maybe using watchlists?

I don't have much time now to work on it, but PRs are welcome!

**Comment by egonw** [comment]
@maxlath only get `getRevisions` would already fit my current needs! I'm afraid I will not find time to make a PR, tho, as I'm struggling to find enough hacking time for my own OS projects :(

**Comment by maxlath** [comment]
ok, I gave it a shot as a morning warm up ^^
* wikidata-sdk: [`getRevisions`](https://github.com/maxlath/wikidata-sdk/blob/master/docs/get_revisions.md)
* wikidata-cli: [`wd revisions`](https://github.com/maxlath/wikidata-cli/blob/master/docs/read_operations.md#wd-revisions)

**Comment by egonw** [comment]
Hi @maxlath, sorry that I did not reply since then. Back in June I was horribly busy and that did not get much better since, but I've [started using your wikidata-sdk in teaching](https://github.com/egonw/scientificProgramming/blob/master/wikidata.template.html) and happy this is now part of the release!

**Comment by maxlath** [comment]
no problem :) feel free to re-open this issue if the proposed solution is lacking regarding your needs
