### ISSUE TITLE
Add option to set botflag on commits

### ISSUE THREAD

**Issue by Peuc** [maxlath/wikidata-cli#29]
A bit of background first: I'm currently running an import using `wikidata-cli`, with a properly identified bot account. Today, an user asked me why contributions appear as coming from a human while it's done by a flagged bot. After a bit of digging, I discovered changesets, along with summary, minor edit flags, (…) also have a botflag value. This value must be set to true for every modification done by a bot, so it doesn't appear in default [recent changes](https://www.wikidata.org/wiki/Special:RecentChanges) view. And it's a [requirement](https://www.wikidata.org/wiki/Wikidata:Bots#All_bots)…
I digged into wikidata-cli, but I found no way to force this flag to be set, so I'm pretty much stuck.

Now comes my enhancement request:
Is there a way to add such an option into wikidata-cli?
I spent about 30 minutes looking through the wikidata-cli source code, to check how this could hypothetically be implemented.
As a first guesstimate, a good option would be to add a boolean entry in `config.json` file that indicates if bot flag must be set or not for the given user credentials. This could be added into `data` structure given to `wikidata-edit`'s `request.js`'s `actionPost()`.

That's where I'm for now.
Any thoughts?

**Comment by maxlath** [comment]
@Peuc I tried to address this issue by letting the user set a `bot=true` flag in `wikidata-edit` via `wikidata-cli` config: see f286d9f and https://github.com/maxlath/wikidata-edit/commit/5b68399, could you test it with your bot account? I don't have one so can't make the tests. Suggested steps to test:

```sh
cd /tmp
git clone https://github.com/maxlath/wikidata-cli -b botFlags
cd wikidata-cli
npm install
# Re-install wikidata-edit to use the botFlags branch
npm install wikidata-edit@https://github.com/maxlath/wikidata-edit#botFlags
# Use the instance we just installed of wikidata-cli
./bin/wd config bot true
# Trying anything
./bin/wd add-claim Q4115189 P921 Q34679
```

**Comment by Peuc** [comment]
Wow, thanks for your patch!
The import to Wikidata is still ongoing, here. It's half done, so it will be finished in about two days.

In order to not interfere in the process, I will test your branch afterwards.

**Comment by maxlath** [comment]
ok, keep me updated then :)

**Comment by maxlath** [comment]
I tried to fix this issue: 1907bcd
Can you try to update `wikidata-edit`? simply re-run 
```sh
npm install wikidata-edit@https://github.com/maxlath/wikidata-edit#botFlags
```

**Comment by Peuc** [comment]
```
$ npm install wikidata-edit@https://github.com/maxlath/wikidata-edit#botFlags
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ wikidata-edit@1.8.1
added 115 packages and updated 1 package in 12.555s
```
Exact same behaviour.

I did two checks that may help you:
- adding `delete config.bot` into wikidata-edit `index.js:13` doesn't help
- rollback `request.js:59` to remove `bot` actually remove bot flag into commit (yeah, better to double check :) )

**Comment by maxlath** [comment]
I [refactored a bit `wikidata-edit` to make it more testable on the bot config behavior](https://github.com/maxlath/wikidata-edit/commit/5e150f6), and it now looks like it generates the expected URLs `bot` flag and body `assert` parameter, can you confirm?

**Comment by Peuc** [comment]
Absolutely, this new version works as expected.
Is there a reliable way to auto-detect the bot flag if the `bot` value is not set in `config.json`, instead of asserting it's not a bot?

**Comment by maxlath** [comment]
I have no idea, I added the `assert` parameter because, at some point , edits where failing to detect the user who made the edit and I was told that the fix was to use `assert=user`, but it's not very clear in which case it is or isn't needed. Is the fact that it's not auto-detecting a blocking issue, or would that just be a nice to have?

**Comment by Peuc** [comment]
This is nowhere near a requirement, the patch fulfills all my needs as it.

Thank you very much for this!

**Comment by maxlath** [comment]
you are very welcome :)
