### ISSUE TITLE
add claim doesn't accept datetime value

### ISSUE THREAD

**Issue by HakanIST** [maxlath/wikidata-cli#30]
Hello,

add claim doesn't accept any of the combinations of date formats such as 1972-12-15. Tested for P569 (date of birth).
Thanks!

**Comment by maxlath** [comment]
this was [fixed in `wikidata-edit`](https://github.com/maxlath/wikidata-edit/commit/94c13f0dee448475b4e83ff25bebf81a72d8903d) and should be fixed in `wikidata-cli` v5.0.0
