### ISSUE TITLE
add claim doesn't support monolingual text

### ISSUE THREAD

**Issue by jhsoby** [maxlath/wikidata-cli#33]
Similar to issue #30 in that it's about an unsupported datatype.

The datatype monolingual string requires a two parts: A language code and a string. It's currently not possible to add that via this tool (or, alternatively, I don't know the correct syntax to do so). In QuickStatements, the syntax to do this is `languagecode:"string"`, perhaps the same syntax should be used here? Tested with [P1705](https://www.wikidata.org/wiki/Property:P1705).

**Comment by jhsoby** [comment]
Oh, and similarly, we need some syntax for how to add this for create-item.

**Comment by maxlath** [comment]
The monolingual text claim issue got fixed by 18aa868, see the [rich claim value documentation](https://github.com/maxlath/wikidata-cli/blob/master/docs/write_operations.md#rich-values)

And for `create-item` (and now also `edit-item`), the updated documentation is [here](https://github.com/maxlath/wikidata-cli/blob/master/docs/write_operations.md#item)

**Comment by jhsoby** [comment]
Thank you very much! :+1:

**Comment by maxlath** [comment]
you're welcome :)

**Comment by jhsoby** [comment]
Sorry to bother you about this again, but I'm not getting this to work with `create-item`. I'm wondering if I'm doing something wrong, or if it is a bug. The command I'm trying is this:

`{"labels":{"nb":"Lundeborg"},"descriptions":{"nb","etternavn"},"claims":{"P1705":{"text":"Lundeborg","language":"mul"}}}`

With `add-claim` it works as it should.

**Comment by maxlath** [comment]
And its was indeed a bug in  `wikidata-edit`, that was fixed in https://github.com/maxlath/wikidata-edit/commit/570b2d1d7be2b62af3caff8618cf06845b3827ca

The patch was published in `wikidata-cli v5.7.2`. Thank you for spotting and sorry for the trouble!

**Comment by jhsoby** [comment]
@maxlath [It's working](https://www.wikidata.org/w/index.php?title=Q46971029&oldid=614307981), hurrah! Thank you very much, and happy new year to you! :-)

**Comment by maxlath** [comment]
you're welcome! :D 
happy new year to you too!
