### ISSUE TITLE
Commands could also handle properties

### ISSUE THREAD

**Issue by pmackay** [maxlath/wikidata-cli#36]
It would be useful to have commands like `summary`, `label`, etc operate on properties as well as items. Does this seem a reasonable idea?

**Comment by maxlath** [comment]
that should already be the case no?
![prop](https://user-images.githubusercontent.com/1596934/32356215-e15f4204-c033-11e7-8a71-c24f0c90f661.png)

**Comment by pmackay** [comment]
Weird! I thought I tried a command like that and got an error. Great!
