### ISSUE TITLE
add-reference parses urls with & in it

### ISSUE THREAD

**Issue by HakanIST** [maxlath/wikidata-cli#37]
Hello, when I try following command  to add reference URL (P854)  as the url has & in it, it doesn't accept it as a valid parameter.

wd add-reference 'Q29062$17048767-D192-4294-9B31-861DE5979A7A' P854 'http://www.tff.org/Default.aspx?pageId=30&kisiId=28050'

**Comment by maxlath** [comment]
fixed! b93e37e
the patch was just published in v5.0.1
