### ISSUE TITLE
Problem when I try to install Wikidata-cli

### ISSUE THREAD

**Issue by nicaogr** [maxlath/wikidata-cli#47]
Hi,

When I try to install wikidata-cli with this command on Ubuntu 16.04 "sudo npm install -g wikidata-cli" I get a message error of this kind : 
"npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/maxlath/commander.js.git /home/gonthier/.npm/_cacache/tmp/git-clone-a1c0dfdb
npm ERR! /home/gonthier/.npm/_cacache/tmp/git-clone-a1c0dfdb/.git: Permission non accordée
"

It seems to be a permission denied error. 

You can found the log file attached. 

Do you have any idea of the origin of this problem ?

Thanks,
[2017-12-22T12_47_59_002Z-debug.log](https://github.com/maxlath/wikidata-cli/files/1582503/2017-12-22T12_47_59_002Z-debug.log)

**Comment by maxlath** [comment]
hello, can you try to re-install now? the issue might have been fixed by 2db8079

**Comment by nicaogr** [comment]
Hello,

I have re-install nodejs with [nvm](https://github.com/creationix/nvm) and then the last version of wikidata-cli with nvm too and that works fine. 

Thanks a lot.
