### ISSUE TITLE
Use commander and chalk for command line tools

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-cli#5]
I use the node packages commander and chalk for wikidata-taxonomy. Asked by a German Wikipedia to create a command line tool to get coordinates of a Wikidata item, I created another script using these packages and I would like to make it part of wikidata-cli:

https://github.com/nichtich/wikidata-cli/tree/wdcoords

would you mind adding commander and chalk as dependencies? I think the other scripts can also benefit from them.

**Comment by maxlath** [comment]
(sorry for the delayed answer, I missed the notification somehow)

Yes! I was already considering `commander` indeed!
What about using it to restructure the whole `wikidata-cli` à la `git` with one root command (`wd`?), and [subcommands](https://github.com/tj/commander.js#git-style-sub-commands)?

`chalk`'s needs is already covered by `colors.js` but I wouldn't mind trying it in this project :)

**Comment by nichtich** [comment]
Yes, subcommands is a good idea but it may be easier to start moving one command after another. Maybe start with `wdprops` and `wdsparql` as they already start with `wd` ;-)

**Comment by maxlath** [comment]
I started working on commander integration in a dedicated branch [commander](https://github.com/maxlath/wikidata-cli/tree/commander), would love to have your feedback on that before publishing it as `v2.0.0` :)

**Comment by nichtich** [comment]
Looks great. I am not sure about `lib/strings` but don't no better way to repeat its content. We could implement global options such as `--language` and `--clipboard` by subclassing `commander and move some other functionality common to all commands to this subclass - but this is refactoring.

**Comment by maxlath** [comment]
Closing this issue: solved by 6f29435 (and following commits) for `commander`, and b4f6d8e for `chalk`.
Support for `-l, --lang` was added by d25724f, d34cfa3, and 4f5e805.
The discussion on `--clipboard` can continue in #4
