### ISSUE TITLE
Writing Time/Date to WD Records

### ISSUE THREAD

**Issue by scottythered** [maxlath/wikidata-cli#52]
I'm running into some issues adding claims with time/date data.

For example, `wd ac Q50278901 P580 "1983"` will result in writing `"time": "+1983-00-00T00:00:00Z"` to the WD record, but WD will not accept YYYY-MM-DD -- or any variations of it -- as a date format: 

![image](https://user-images.githubusercontent.com/11927373/37061240-6e89d3ee-2158-11e8-87b6-7618e12f3f54.png)

**Comment by maxlath** [comment]
weird, I can't reproduce the issue, all the following commands should pass:
```sh
wd ac Q4115189 P580 "1983"
wd ac Q4115189 P580 "1983-02"
wd ac Q4115189 P580 "1983-02-23"
```
which version of `wikidata-cli` and `wikidata-edit` (in wikidata-cli `node_modules` folder) are you using?
```sh
wd --version
cat path/to/wikidata-cli/node_modules/wikidata-edit/package.json | grep 'version":'
```

**Comment by scottythered** [comment]
wd: 4.19.1
wikidata-edit: 1.9.0

**Comment by maxlath** [comment]
aaah ok, [`wd` accepts month or day precision only since v5.0.0](https://github.com/maxlath/wikidata-cli/blob/master/CHANGELOG.md#500---2017-11-03) :)
can you try to update and confirm that it solves the issue?

**Comment by scottythered** [comment]
Hahaha well that was fixed fast!

**Comment by scottythered** [comment]
Love this program, by the way

**Comment by maxlath** [comment]
thank you :D
