### ISSUE TITLE
Instructions for Lexemes

### ISSUE THREAD

**Issue by belett** [maxlath/wikidata-cli#69]
Hi,

Would it be possible to have instructions for Lexemes? Or at least to think about it ;)

There is no tool right now, probably because the API is not fully ready and still unstable. SO it would be nice if CLI could fill this gap.

**Comment by maxlath** [comment]
closing this issue as it's a duplicate of #57
it could be that I take the opportunity of this wmhack edition to give it a shot but can't promise ;)
