### ISSUE TITLE
somevalue/novalue times work for adding qualifiers, but not updating

### ISSUE THREAD

**Issue by generalist** [maxlath/wikidata-cli#73]
It looks like the somevalue/novalue functions only work with some of the command types.

`wd aq 'Q26722044$EF142B3D-0FE3-4A8F-97B8-2722A6F33BD9' P582 '{"snaktype":"somevalue"}'` 

This works as expected and adds an "unknown value" P582 qualifier.

 `wd uq 'Q26722044$EF142B3D-0FE3-4A8F-97B8-2722A6F33BD9' P582 '1848-12-31' '{"snaktype":"somevalue"}'`

This throws an error "TypeError: Cannot read property 'replace' of undefined".

I'm not sure from the documentation if this is intended or not (it mentions somevalue/novalue next to add-qualifier, so perhaps it is?)

And thanks as always, it's a great tool :-)

**Comment by maxlath** [comment]
yes, special snaktypes haven't been implemented everywhere yet: here it's the [`findSnak`](https://github.com/maxlath/wikidata-edit/blob/master/lib/claim/find_snak.js) that isn't aware of special snaktypes. working on it :)

**Comment by generalist** [comment]
Awesome - glad to know you have it in hand :-)

**Comment by Jheald** [comment]
+1 for this.  It would be a particularly useful feature to be able to change <somevalue> to a Qid using wd uq, with the qualifiers and references just carrying over.

**Comment by maxlath** [comment]
done! published in `v7.5.0`
