### ISSUE TITLE
Is it possible to create 'somevalue' claims with wd edit-item ?

### ISSUE THREAD

**Issue by Jheald** [maxlath/wikidata-cli#75]
When I try

wd edit-item '{"id":"Q63313825", "claims":{"P767": {"value": {"snaktype":"somevalue"}, "qualifiers": {"P1932": "UBL, E."}, "references":  {"P248": "Q53556514", "P5199": "000011361", "P813": "2019-03-06"} } } }' 

I get the error "Error: invalid wikidata id: [object Object]"

Similarly with the simpler

wd edit-item '{"id":"Q63313825", "claims":{"P767": {"value": {"snaktype": "somevalue"} } } }'

What is the correct syntax for adding a claim with value 'somevalue' using wd edit-item?  Is it in fact possible?

**Comment by maxlath** [comment]
yes it is: `snaktype` should be at the reference object root and `value` shouldn't be set, see [example here](https://github.com/maxlath/wikidata-cli/issues/74#issuecomment-490412310)

**Comment by Jheald** [comment]
Thank you.  That was the problem.  Edits now successfully made!
