### ISSUE TITLE
Add wd-values command

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-cli#8]
As suggested in https://github.com/maxlath/wikidata-cli/pull/6#issuecomment-242840170 a command similar to wd-claims to only get statement values.

**Comment by maxlath** [comment]
couldn't that simply be an other option on wd-claims?
```
$ wd claims Q2112 P625 --format values
52.016666666667 8.5166666666667
$ wd claims Q2112 P625 --format degrees
52°01'0.00" 8°31'0.00"
```

**Comment by nichtich** [comment]
In fact. We can still create an alias later.
