### ISSUE TITLE
writting properties files may trigger EACCES: permission denied errors

### ISSUE THREAD

**Issue by maxlath** [maxlath/wikidata-cli#9]
created a dedicated thread for this issue discussion started in [here](https://github.com/maxlath/wikidata-cli/pull/6#issuecomment-242910914)
@nichtich:

> there is a bug if you installed wikidata-cli globally:
> 
> ```
> $ qclaims Q2112 P625
> Error: EACCES: permission denied, open '/usr/local/lib/node_modules/wikidata-cli/props/de.json'
>     at Error (native) 
> Context:
>  undefined
> ```

@maxlath:

> Damn, I didn't see that "permission denied" message coming: I installed node with [nvm](https://github.com/creationix/nvm) which setups node modules in the home folder `/home/username/.nvm/versions/node/v4.4.5/lib/node_modules/wikidata-cli/props/de.json`. Would the solution be to create a dedicated folder in the user home (like `/home/username/.wikidata-filter`) where we would have the right to write anything that we need?
> Fyi, another consumer of those properties files is [wdprops](https://github.com/maxlath/wikidata-cli#wdprops) and the properties are [taken fresh out of the SPARQL endpoint](https://github.com/maxlath/wikidata-cli/blob/master/lib/queries/all_properties.js): we got to cache that in some way to avoid spamming the endpoint with what starts to be a heavy query, thus the use of local files.

**Comment by maxlath** [comment]
@nichtich did you install node using `sudo`?

**Comment by nichtich** [comment]
I think so

**Comment by maxlath** [comment]
so I guess you had to install `wikidata-cli` using sudo too, that would explain the higher level of authorization required: `wd claims` or `wd props` would thus probably work if prefixed by sudo at least every time properties are requested in a new language. Further accesses will probably not require it as it would only be read operations

**Comment by nichtich** [comment]
Yes, that's a workaround. If wd will include other write-to-disk operations (wikidata-token?) it may stil worth to reconsider using a file location based on current user.

**Comment by maxlath** [comment]
or run `chmod 666 ./props` during the `postinstall` script?

**Comment by maxlath** [comment]
reverted dcdbaa8 with d97498d: using `chmod` during `postinstall` doesn't seem to be an option
